### ISSUE TITLE
"datatype" CHUNK

### ISSUE THREAD

**Issue by dsyleixa** [yahesh/cryptuino#1]
IMO using a "datatype" CHUNK is confusing and makes the code weird and quite unreadable.
Why don't you drop that and substitute it by the genuine datatype uint8_t ?

**Comment by yahesh** [comment]
There are 3 reasons to do this:

1. It simplifies modification for different platforms. This library is primarily meant to be used on Arduinos (ATMEL) and therefore caters for the restricted memory on that platform by only supporting up to 255 memory slots (aka. chunks) and a maximal chunk size of 255 bytes. However, on platforms with more RAM available it might be helpful to have more memory slots or bigger memory slots available. Instead of rewriting the whole code you'd only have to redefine CHUNK and CHUNK_SIZE to, say uint16_t to increase the number of available chunks to 2^16-1 and the maximum size of a single chunk to 2^16-1.

2. Introducing those defines helps to differentiate between different uses of the same type. Take for example the definition of the function `alloc_chunk()` which could be written as `uint8_t alloc_chunk(uint8_t size)`. Thanks to the self-explanatory name of the function and the parameter you know that it allocates a new memory slot/chunk with the given size. But what is the return value meant to represent? Thanks to the used type identifier in the actual defintion `CHUNK alloc_chunk(CHUNK_SIZE size)` you can derive from the function definitions where this value is meant to be used, like in `bool resize_chunk(CHUNK number, CHUNK_SIZE size)` or `bool copyOffsetLength_chunk(CHUNK source, CHUNK destination, CHUNK_SIZE sourceOffset, CHUNK_SIZE destinationOffset, CHUNK_SIZE length);`.

3. It's implemented as a macro. Thus, all occurences will be replaced by the preprocessor before the actual compiler kicks in. So if you don't like to use `CHUNK`, `CHUNK_SIZE` or whatever in your code then just use `uint8_t`. It shouldn't make any difference.

**Comment by dsyleixa** [comment]
I know how #define macros work, but the naming is not intuitively understandable and not easily detectable.
CHUNK does not dignify anything meaningful, e.g. tInt would be better.
OTOH IMO using #defines (anyway if obscured or not) are generally a bad practice anyway, better would be using templates or typedefs, e.g.
`typedef tInt uint8_t;`
as to me, this would be reasonable then:
`#define tIntSize sizeof(tInt)`

and all those type defines I would suggest to put into a seperate header file
cryptdefs.h

**Comment by yahesh** [comment]
IMHO `tInt` wouldn't be better thank the current `CHUNK`, but I guess this is a matter of taste - as is using `define` instead of `typedef` for this case of usage. At least I couldn't find any source that says that using the preprocessor for this kind of stuff is considered bad practice.

Furthermore I don't see that putting the keyword definitions in separate header file like `cryptdefs.h` would be helpful either. There is a clear hierarchy of dependencies: `memuino -> chunkuino -> arc64uino/base64uino/sha1uino -> outputuino`. Putting the definitions in one place would turn that into one blob of interdependance.

**Comment by dsyleixa** [comment]
As to me I was totally confused about finding a datatype CHUNK in your code...
CHUNK ?? What is that ??? Is that proprietary??  Or is that a new C++ class or datatype I never heard of??

OTOH, tInt or intType or something like that is supposed to indicate that it's just a interger type, not a class or a struct or a container.
